# Generated by Django 5.0.6 on 2024-05-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.TextField(max_length=100)),
                ('LastName', models.TextField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=16)),
                ('Mobile', models.TextField(max_length=10)),
                ('Plan', models.TextField(max_length=20)),
                ('End_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('duration', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to='static/movies')),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
