# Generated by Django 5.0.6 on 2024-05-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscriptionplan_alter_customer_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Plan',
            field=models.CharField(default='Basic', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='LastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
