# Generated by Django 5.0.6 on 2024-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_subscription_remove_customer_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(max_length=100, null='True'),
        ),
    ]
